CREATE DATABASE "CarDealerDatabase";
CREATE SCHEMA IF NOT EXISTS public;

DROP TABLE IF EXISTS location CASCADE;
DROP TABLE IF EXISTS administrator CASCADE;
DROP TABLE IF EXISTS consultant CASCADE;
DROP TABLE IF EXISTS dealer CASCADE;
DROP TABLE IF EXISTS manufacturer CASCADE;
DROP TABLE IF EXISTS offer CASCADE;
DROP TABLE IF EXISTS car CASCADE;
DROP TABLE IF EXISTS dealer_consultant CASCADE;
DROP TABLE IF EXISTS administrator_dealer CASCADE;
DROP TABLE IF EXISTS offer_location CASCADE;
DROP TABLE IF EXISTS dealer_car CASCADE;

CREATE TABLE IF NOT EXISTS location
(
    id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country varchar(20) NOT NULL,
    city    varchar(20) NOT NULL,
    street  varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS administrator
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(20) NOT NULL,
    last_name  varchar(20) NOT NULL,
    phone      int         NOT NULL UNIQUE,
    login      varchar(20) NOT NULL UNIQUE,
    password   varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS manufacturer
(
    id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"           varchar(30) NOT NULL,
    country          varchar(30) NOT NULL,
    origination_year int         NOT NULL
);

CREATE TABLE IF NOT EXISTS consultant
(
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      varchar(20) NOT NULL,
    last_name       varchar(20) NOT NULL,
    phone           int         NOT NULL UNIQUE,
    login           varchar(20) NOT NULL UNIQUE,
    password        varchar(20) NOT NULL,
    rate            numeric     NOT NULL,
    manufacturer_id int         REFERENCES manufacturer (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS dealer
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id int         REFERENCES location (id) ON DELETE SET NULL,
    is_open     boolean     NOT NULL DEFAULT FALSE,
    hours       varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS offer
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount      int         NOT NULL,
    description varchar(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS car
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    engine       json        NOT NULL,
    color        varchar(30) NOT NULL,
    brand        varchar(20) NOT NULL,
    country      varchar(30) NOT NULL,
    price        int         NOT NULL,
    is_available boolean     NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS dealer_consultant
(
    dealer_id     int REFERENCES dealer (id) ON DELETE CASCADE,
    consultant_id int REFERENCES consultant (id) ON DELETE CASCADE,
    CONSTRAINT dealer_consultant_pk PRIMARY KEY (dealer_id, consultant_id)
);

CREATE TABLE IF NOT EXISTS administrator_dealer
(
    administrator_id int REFERENCES administrator (id) ON DELETE CASCADE,
    dealer_id        int REFERENCES dealer (id) ON DELETE CASCADE,
    CONSTRAINT administrator_dealer_pk PRIMARY KEY (administrator_id, dealer_id)
);

CREATE TABLE IF NOT EXISTS offer_location
(
    offer_id    int REFERENCES offer (id) ON DELETE CASCADE,
    location_id int REFERENCES location (id) ON DELETE CASCADE,
    CONSTRAINT offer_location_pk PRIMARY KEY (offer_id, location_id)
);

CREATE TABLE IF NOT EXISTS dealer_car
(
    dealer_id int REFERENCES dealer (id) ON DELETE CASCADE,
    car_id    int REFERENCES car (id) ON DELETE CASCADE,
    CONSTRAINT dealer_car_pk PRIMARY KEY (dealer_id, car_id)
)